name: publish
on:
  release:
    # both releases and prereleases
    types: [published]
  # support manual publish in case something goes wrong
  workflow_dispatch:
    inputs:
      tag:
        description: GitHub tag to publish (e.g. @simplysf/simply@2.2.1)
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || inputs.tag }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci --ignore-scripts

      - run: npm run build

      - name: Publish packages with new git tags
        run: npx lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
